"""Turn public tau-bench trajectories into Evalkeep traces and replay targets.

tau-bench runs the same 165 retail and airline customer-service tasks against
many models and scores each run by comparing the final database state with the
expected one. That gives the two halves a regression suite needs and that most
public agent data has only one of: what the agent was asked and did, and an
independent verdict on whether it worked.

    python prepare.py                     # two models, ~8 MB
    python prepare.py --model <name> ...  # any models from the dataset card

Writes, per model, `<model>.traces.jsonl` and `replay_<model>.py`. The replay
target returns what that model actually did, so `evalkeep compare` scores two
recorded systems rather than a simulation of them.

Source: https://huggingface.co/datasets/AgentSuite/tau-bench-trajectories
"""

from __future__ import annotations

import argparse
import ast
import itertools
import json
import re
import urllib.parse
import urllib.request
from pathlib import Path

BASE = "https://huggingface.co/datasets/AgentSuite/tau-bench-trajectories/resolve/main"
DEFAULT_MODELS = ("Qwen3-235B-A22B-FP8", "claude-4.5-sonnet-thinking-off")

# Evalkeep redacts before it stores, so the prompt a generated test carries is
# not byte-identical to the one the recorded agent saw -- on this data 27 of 165
# differ, because the instruction contains an email address. Matching on letters
# alone survives that: it drops the addresses, the markers that replaced them,
# and the punctuation around both, which is what actually moves.
REDACTED = re.compile(r"\[REDACTED:[^\]]*\]|[\w.+-]+@[\w.-]+")
LETTERS = re.compile(r"[a-z]+")

TARGET = '''"""Replay of {model} on tau-bench. Generated by prepare.py."""

import json
import os
import re

_INDEX = json.load(open(os.path.join(os.path.dirname(__file__), "{index}")))
_REDACTED = re.compile(r"\\[REDACTED:[^\\]]*\\]|[\\w.+-]+@[\\w.-]+")
_LETTERS = re.compile(r"[a-z]+")


def call_api(prompt, options=None, context=None):
    """Return what {model} actually did for this task.

    A prompt with no recorded trajectory raises rather than returning nothing.
    Returning nothing would *pass* every test built from "must not do X", so a
    lookup failure would read as a perfect score.
    """
    key = " ".join(_LETTERS.findall(_REDACTED.sub(" ", str(prompt)).lower()))
    record = _INDEX.get(key)
    if record is None:
        raise LookupError("no recorded trajectory for this prompt")
    return {{"output": {{"text": record["text"], "toolCalls": record["toolCalls"]}}}}
'''


def instruction(meta: dict) -> str:
    """The task the simulated customer was given, which is the request."""
    raw = meta.get("task_description")
    if isinstance(raw, str):
        try:
            raw = ast.literal_eval(raw)
        except (ValueError, SyntaxError):
            return raw[:2000]
    return (raw or {}).get("instruction", "")[:2000] if isinstance(raw, dict) else str(raw)[:2000]


def key_for(text: str) -> str:
    return " ".join(LETTERS.findall(REDACTED.sub(" ", text).lower()))


def download(model: str, into: Path) -> Path:
    destination = into / f"{model}.jsonl"
    if destination.exists():
        return destination
    url = f"{BASE}/{urllib.parse.quote(model)}.jsonl"
    print(f"  downloading {model} ...")
    with urllib.request.urlopen(url, timeout=180) as response:
        destination.write_bytes(response.read())
    return destination


def tool_calls(message: dict) -> list[dict]:
    calls = []
    for call in message.get("tool_calls") or []:
        function = call.get("function") or {}
        try:
            arguments = json.loads(function.get("arguments") or "{}")
        except json.JSONDecodeError:
            arguments = {}
        calls.append(
            {
                "id": call.get("id"),
                "tool": function.get("name") or "unknown",
                "arguments": arguments if isinstance(arguments, dict) else {},
            }
        )
    return calls


def convert(model: str, source: Path, into: Path) -> tuple[int, int]:
    traces_path = into / f"{model}.traces.jsonl"
    index: dict[str, dict] = {}
    failures = 0

    with traces_path.open("w", encoding="utf-8") as out:
        for row in (json.loads(line) for line in source.open(encoding="utf-8")):
            meta, verdict = row["meta"], row["eval_result"]
            score = verdict.get("score")
            passed = score is not None and score >= 1.0
            failures += not passed

            events: list[dict] = []
            counter = itertools.count(1)
            final = ""
            replay: list[dict] = []
            for message in row["messages"]:
                role = message.get("role")
                if role == "system":
                    continue
                body = message.get("content") or ""
                if role in {"user", "assistant"} and body:
                    if role == "assistant":
                        final = body
                    events.append(
                        {
                            "event_id": f"e{next(counter)}",
                            "type": "message",
                            "role": role,
                            "content": body[:4000],
                        }
                    )
                for call in tool_calls(message):
                    replay.append({"tool": call["tool"], "arguments": call["arguments"]})
                    events.append(
                        {
                            "event_id": f"e{next(counter)}",
                            "type": "tool_call",
                            "call_id": call["id"],
                            "tool": call["tool"],
                            "arguments": call["arguments"],
                        }
                    )
                if role == "tool":
                    events.append(
                        {
                            "event_id": f"e{next(counter)}",
                            "type": "tool_result",
                            "call_id": message.get("tool_call_id"),
                            "tool": message.get("name") or "unknown",
                            "result": body[:4000],
                        }
                    )

            text = instruction(meta)
            # `db_match` is False on tasks that never write to the database, so
            # it is recorded beside the verdict rather than read as one. Treated
            # as a failed check on its own it invented 23 failures the benchmark
            # had scored as passes.
            matched = "matched" if verdict.get("db_match") else "did not match"
            out.write(
                json.dumps(
                    {
                        "trace_id": f"{model}--{row['task_name']}-{meta.get('task_id')}",
                        "input": {"text": text or f"tau bench task {meta.get('task_id')}"},
                        "output": {"text": final[:4000]} if final else {},
                        "events": events,
                        "outcome": {
                            "status": "success" if passed else "failure",
                            "evaluations": [
                                {
                                    "name": "tau_bench_reward",
                                    "passed": passed,
                                    "score": score,
                                    "reason": f"task reward {score}; final database state {matched}",
                                }
                            ],
                        },
                        "metadata": {
                            "source": "tau-bench",
                            "model": model,
                            "tags": [row["task_name"]],
                        },
                    },
                    ensure_ascii=False,
                )
                + "\n"
            )
            indexed = text or f"tau bench task {meta.get('task_id')}"
            index[key_for(indexed)] = {"text": final[:4000], "toolCalls": replay}

    slug = model.replace(".", "_").replace("-", "_")
    (into / f"index_{slug}.json").write_text(json.dumps(index))
    (into / f"replay_{slug}.py").write_text(
        TARGET.format(model=model, index=f"index_{slug}.json")
    )
    return failures, len(index)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", action="append", dest="models", metavar="NAME")
    parser.add_argument("--into", type=Path, default=Path("."), metavar="DIR")
    args = parser.parse_args()
    models = args.models or list(DEFAULT_MODELS)
    args.into.mkdir(parents=True, exist_ok=True)

    print(f"tau-bench: {len(models)} model(s)")
    for model in models:
        source = download(model, args.into)
        failures, tasks = convert(model, source, args.into)
        slug = model.replace(".", "_").replace("-", "_")
        print(f"  {model}: {tasks} tasks, {failures} failed -> replay_{slug}.py")

    first = models[0]
    print(f"\nNext:\n  evalkeep init\n  evalkeep from-traces {first}.traces.jsonl")


if __name__ == "__main__":
    main()
